### ISSUE TITLE
TabNine consumes too much CPU

### ISSUE THREAD

**Issue by drnguyen** [codota/TabNine#110]
![image](https://user-images.githubusercontent.com/15685704/62113640-3b95ab80-b2b5-11e9-98b7-73d4029e004e.png)

This is on a Splunk app project with JS, python code.

**Comment by International** [comment]
I am seeing the same behaviour on ruby projects, at least 1 CPU uses 100%

**Comment by amircodota** [comment]
We've made several improvements since regarding cpu and memory consumption of TabNine.

Can you verify that your issue is fixed?

**Comment by International** [comment]
Seems alleviated, thought not yet ready to say it's fixed.

**Comment by International** [comment]
I would say not fixed, have seen plenty of times where it uses 600% of CPU.

**Comment by amircodota** [comment]
@International Did you see it go to 600% while typing, or when idle?

**Comment by International** [comment]
One of the times it went to 600% I checked activity monitor,tabnine was not in the top 10-15 processes. I was writing code, was in a meeting, then added a new ruby gem as dependency and the fan turned on. Tabnine was using 600%. Seems there is some kind of predisposition to use so much cpu after not writing code for some time. Had a few moments even today when it was using 400%.

**Comment by amircodota** [comment]
@International That's great feedback.

Do you remember which ruby gem it was?
Was this an open source project by any chance? What editor are you using? 
Would love to try the exact same use case myself.

**Comment by International** [comment]
If I remember correctly, it was https://github.com/chaps-io/gush <https://github.com/chaps-io/gush> .
Regarding the editor, it depends on the size/type of the file. Sometimes I use atom, sometimes vs code, sometimes sublime.
I think I have tabnine configured in all of them.
