### ISSUE TITLE
web login blank screen

### ISSUE THREAD

**Issue by Bysmyyr** [codota/TabNine#514]
https://app.tabnine.com/profile/subscription cannot login, just a blank screen. 

gz#11787

**Comment by pingumen96** [comment]
I confirm the issue, it appears to be a CORS related problem.

**Comment by bilucodota** [comment]
Hi guys, 
Thanks for reaching out!
 Can you please attach a video of what you're experiencing? if you see any errors in console - please attach them as well

**Comment by pingumen96** [comment]
It has been solved the sane day, thank you.

**Comment by Lippiece** [comment]
The issue persists.
![image](https://user-images.githubusercontent.com/47634624/164167556-d1dd454c-2042-44fe-b323-cd0d18298032.png)

**Comment by bilucodota** [comment]
@Lippiece can you please attach the logs on the dev console?

**Comment by Lippiece** [comment]
Here you go. After some time, it redirects to the Tabnine Hub unlogged.

![image](https://user-images.githubusercontent.com/47634624/164170012-da8d6860-c044-448d-81d1-3daac11f5274.png)

[127.0.0.1-1650438207570.log](https://github.com/codota/TabNine/files/8519122/127.0.0.1-1650438207570.log)

**Comment by Lippiece** [comment]
It was fixed by:
1. Clicking "Sign in" from the IDE as usual.
2. Signing in.
3. Waiting for the redirect to http://127.0.0.1:5555/ page.
4. Opening the "Sign in" link from the top of the page **in a new page**.
5. Signing in.

**Comment by tjmaru** [comment]
is there a solution or workaround?
I have the same, after login on the tabnine website I have been redirected to the tabnine config unlogged

**Comment by elotmanik** [comment]
Hi all,
I have the same issue and there is an error on brower console (chrome but even on firefox)
![image](https://user-images.githubusercontent.com/44871676/188487351-8b20449b-d9b9-4db1-9e42-e23babafc452.png)
